/**
 * Source provenance — AGENTS.md §21.
 *
 * Every imported source must record licensing and origin. Never ingest
 * external biblical or scholarly data without it.
 */
export interface SourceProvenance {
  readonly sourceId: string;
  readonly sourceName: string;
  readonly sourceType: string;
  readonly license?: string;
  readonly attribution?: string;
  readonly sourceUrl?: string;
  readonly importedAt: Date;
}

/**
 * A citation attached to generated or retrieved material.
 *
 * AGENTS.md §2: Scripture, interpretation, AI synthesis and user content must
 * remain visibly distinct. `kind` is what preserves that distinction when
 * material is copied, saved or exported.
 */
export interface Citation {
  readonly kind: 'scripture' | 'research-source' | 'lexical' | 'historical';
  readonly label: string;
  readonly sourceId?: string;
  readonly canonicalReference?: string;

  /**
   * The retrieval unit this came from (§20).
   *
   * What makes a citation checkable rather than asserted: a claim traces to a
   * row that was actually retrieved. Zedek's citation validation (§16) rejects
   * a Scripture citation that cannot be resolved back to one, because a
   * reference a model produced unaided is exactly what §2.2 forbids.
   */
  readonly retrievalUnitId?: string;

  /** Which translation, where the citation is Scripture. */
  readonly translation?: string;

  /**
   * The cited text, verbatim as retrieved.
   *
   * Never paraphrased (§22.3), and never re-generated by a model — the point
   * is that a reader can compare it against the passage itself.
   */
  readonly text?: string;
}
